# Generated by Django 3.2.7 on 2021-10-02 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('_id', models.CharField(default='', max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('_id', models.CharField(default='', max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_service.distributor')),
            ],
        ),
    ]
