# Generated by Django 3.2.7 on 2021-10-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='_id',
            field=models.IntegerField(default='', max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='_id',
            field=models.IntegerField(default='', max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(max_length=50),
        ),
    ]
